Add RVMSIS include path to fix core_riscv.h compilation error
Fix missing header file error during compilation:
- Added -I$(SDK_ROOT)/EXAM/SRC/RVMSIS to C_INCLUDES
- This directory contains core_riscv.h required by CH57x_common.h

Error fixed:
  fatal error: core_riscv.h: No such file or directory

The RVMSIS (RISC-V Microcontroller Software Interface Standard)
directory contains the RISC-V core definitions needed for CH57x.